# Configuration
name: "Nome do Projeto"
cms: "A2siteBox/WordPress"
browsers: "Firefox, Chrome, IE8+"
styleguide_url: "/styleguide"
meta_description: "Descrição da meta tag description."
meta_keywords: "Tags da meta tag keywords."

# Menu
menu:
    'Tipografia':
        label: "Tipografia"
        link: "/tipografia/"
        class: "tipografia"
    'Grid':
        label: "Grid"
        link: "/grid/"
        class: "grid"
    'Botões':
        label: "Botões"
        link: "/botoes/"
        class: "buttons"
    'Formulários':
        label: "Formulários"
        link: "/formularios/"
        class: "forms"
    'Layouts':
        label: "Layouts"
        link: "/layouts/"
        class: "layouts"
    'Navegação':
        label: "Navegação"
        link: "/navegacao/"
        class: "navegacao"
    'Cores':
        label: "Cores"
        link: "/cores/"
        class: "colors"
