"Padrao":
  title: Padrão
  link: "/botoes/#padrao"
  id: "padrao"
  subtitle: Botão padrão básico do projeto. Aplicado nas tags <code>a</code> <code>button</code> e <code>input</code>.
  sourceCode: button-default.html.twig

"Cores":
  title: Cores
  link: "/botoes/#cores"
  id: "cores"
  subtitle: Variações de cores do botão.
  sourceCode: button-colors.html.twig

"Tamanho":
  title: Tamanhos
  link: "/botoes/#tamanhos"
  id: "tamanhos"
  subtitle: Variações de tamanhos de botões.
  sourceCode: button-size.html.twig

"Redes sociais":
  title: Redes sociais
  link: "/botoes/#redes-sociais"
  id: "redes-sociais"
  subtitle: Botões de compartilhamento que usam apenas o link sem scripts externos
  sourceCode: button-social.html.twig

"Redes sociais sem texto":
  title: Redes sociais sem texto
  link: "/botoes/#redes-sociais-sem-texto"
  id: "redes-sociais-sem-texto"
  sourceCode: button-social-simple.html.twig

"Redes sociais menor":
  title: Redes sociais menor
  link: "/botoes/#redes-sociais-menor"
  id: "redes-sociais-menor"
  sourceCode: button-social-small.html.twig

"Redes sociais sem texto menor":
  title: Redes sociais sem texto menor
  link: "/botoes/#redes-sociais-sem-texto-menor"
  id: "redes-sociais-sem-texto-menor"
  sourceCode: button-social-simple-small.html.twig
