"form inputs":
  title: Inputs
  link: "/formularios/#inputs"
  id: "inputs"
  subtitle: "Padrão para exibição de elementos <strong>input</strong> <code>text</code>, <code>email</code>, <code>password</code>, <code>search</code>, <code>tel</code>, <code>url</code>, <code>date</code>, <code>datetime</code>, <code>datetime-local</code>, <code>month</code> e <code>week</code>."
  sourceCode: 01-inputs.html.twig

"form selects":
  title: Select
  link: "/formularios/#selects"
  id: "selects"
  subtitle: Padrão para exibição de elementos <strong> select</strong>.
  sourceCode: 02-selects.html.twig

"form textarea":
  title: Textarea
  link: "/formularios/#textarea"
  id: "textarea"
  subtitle: Padrão para exibição de elementos <strong>textarea</strong>.
  sourceCode: 03-textarea.html.twig

"form radio":
  title: Input radio
  link: "/formularios/#radio"
  id: "radio"
  subtitle: Padrão para exibição de elementos input do tipo <strong>radio</strong>.
  sourceCode: 04-radio.html.twig

"form checkbox":
  title: Input checkbox
  link: "/formularios/#checkbox"
  id: "checkbox"
  subtitle: Padrão para exibição de elementos input do tipo <strong>checkbox</strong>.
  sourceCode: 05-checkbox.html.twig

"form basico":
  title: Formulário básico
  link: "/formularios/#form-basico"
  id: "form-basico"
  subtitle: Padrão para formulários.
  sourceCode: 06-formulario.html.twig

"form busca":
  title: Formulário de busca
  link: "/formularios/#form-busca"
  id: "form-busca"
  subtitle: Padrão para formulários de busca.
  sourceCode: 07-busca.html.twig
