"Tabs":
  title: Tabs
  link: "/navegacao/#tabs"
  id: "tabs"
  subtitle: Navegação por tabs
  sourceCode: tabs.html.twig

"Accordion":
  title: Accordion
  link: "/navegacao/#accordion"
  id: "accordion"
  subtitle: Navegação por accordion.
  sourceCode: accordion.html.twig
